[package]
name = "winpackage"
version = "0.1.0"
edition = "2024"

[dependencies]

windows = { version = "0.54" }
clap = { version = "4.5.20", features = ["derive"] }
bytemuck ={ version = "*", features = ["derive"] } # <-- savve casting